DROP DATABASE IF EXISTS WRITERS;
CREATE DATABASE WRITERS;
USE WRITERS;

CREATE TABLE WRITER (
id INT(11) NOT NULL AUTO_INCREMENT,
firstname NVARCHAR(50) NOT NULL,
lastname NVARCHAR(50) NOT NULL,
patronymic NVARCHAR(50) DEFAULT NULL,
PRIMARY KEY (id)
) ;

CREATE TABLE STYLE (
id INT(11) NOT NULL AUTO_INCREMENT,
name NVARCHAR(50) NOT NULL,
PRIMARY KEY (id)
) ;

CREATE TABLE WRITER_STYLE (
writer_id INT(11) NOT NULL,
style_id INT(11) NOT NULL,
FOREIGN KEY (writer_id) REFERENCES WRITER (id) ON DELETE CASCADE,
FOREIGN KEY (style_id) REFERENCES STYLE (id) ON DELETE CASCADE
) ;

INSERT INTO WRITER VALUES(NULL, "Иван", "Иванов", "Иванович");
INSERT INTO WRITER VALUES(NULL, "Иван", "Петров", "Петрович");
INSERT INTO WRITER VALUES(NULL, "Иван", "Олегов", "Олегович");
INSERT INTO WRITER VALUES(NULL, "Иван", "Петров", "Олегович");
INSERT INTO STYLE VALUES(NULL, "Биография");
INSERT INTO STYLE VALUES(NULL, "Научно-популярная литература");
INSERT INTO STYLE VALUES(NULL, "Детектив");
INSERT INTO STYLE VALUES(NULL, "Роман");
INSERT INTO STYLE VALUES(NULL, "Научная фантастика");

INSERT INTO WRITER_STYLE VALUES(1, 1);
INSERT INTO WRITER_STYLE VALUES(1, 2);
INSERT INTO WRITER_STYLE VALUES(1, 3);
INSERT INTO WRITER_STYLE VALUES(1, 4);
INSERT INTO WRITER_STYLE VALUES(1, 5);
INSERT INTO WRITER_STYLE VALUES(2, 1);
INSERT INTO WRITER_STYLE VALUES(2, 2);
INSERT INTO WRITER_STYLE VALUES(3, 2);
INSERT INTO WRITER_STYLE VALUES(3, 5);
INSERT INTO WRITER_STYLE VALUES(4, 2);
INSERT INTO WRITER_STYLE VALUES(4, 4);
INSERT INTO WRITER_STYLE VALUES(4, 5);

 #писателей, которые писали во всех жанрах, представленных в таблице
 SELECT WRITER.firstname, WRITER.lastname, WRITER.patronymic FROM WRITER_STYLE, WRITER 
 WHERE WRITER.id = WRITER_STYLE.writer_id
 GROUP BY WRITER_STYLE.writer_id HAVING COUNT(*)=(SELECT COUNT(*) FROM STYLE);
 
 # жанры, в которых писали все
 SELECT STYLE.name FROM WRITER_STYLE, STYLE
 WHERE STYLE.id = WRITER_STYLE.style_id
 GROUP BY WRITER_STYLE.style_id HAVING COUNT(*)=(SELECT COUNT(*) FROM WRITER);
